sudo: false
language: python
python:
    - "2.7"
    - "3.5"
install:
    - pip install -r requirements.txt -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com
script:
    - flake8 ./
    - nosetests -w crawlers -v ./
